# Generated by Django 4.0.5 on 2022-07-07 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstBlog', '0002_blog_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='created_on',
            new_name='createdDate',
        ),
    ]
